print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Schulz/Documents/Unity/it-spiderman/itSpid/Assets/ressources/models/suit03.mb"`)
{		
	file -o "/Users/Schulz/Documents/Unity/it-spiderman/itSpid/Assets/ressources/models/suit03.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Schulz/Documents/Unity/it-spiderman/itSpid/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Schulz/Documents/Unity/it-spiderman/itSpid/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Schulz/Documents/Unity/it-spiderman/itSpid/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
