print "Starting maya loading and fbx conversion \n";
			
if (`file -q -exists "H:/Unity Projects/itSpid/it-spiderman/itSpid/Assets/ressources/models/itspid04_rigged.mb"`)
{
	file -o "H:/Unity Projects/itSpid/it-spiderman/itSpid/Assets/ressources/models/itspid04_rigged.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "H:/Unity Projects/itSpid/it-spiderman/itSpid/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

system ("del \"H:\\Unity Projects\\itSpid\\it-spiderman\\itSpid\\Temp\\CommandPipe\"");

$donepipeKill = `fopen "H:/Unity Projects/itSpid/it-spiderman/itSpid/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
